set nocompatible
set runtimepath^=.
set viminfofile=NONE
syntax on

runtime plugin/jusi.vim

source test/notebook.vim

call Test_parser_detects_cells_and_magic()
call Test_rebuild_places_signs_on_cell_starts()
call Test_insert_below_creates_new_cell()
call Test_insert_above_creates_new_cell()
call Test_delete_middle_cell_keeps_neighbors()
call Test_delete_only_cell_resets_to_single_empty_cell()
call Test_delete_last_cell_moves_to_previous_cell()
call Test_edit_current_clears_cell_body_and_enters_insert_target()
call Test_copy_current_stores_cell_lines()
call Test_paste_below_inserts_copied_cell()
call Test_paste_below_without_clipboard_is_noop()
call Test_navigation_moves_to_cell_boundaries()
call Test_existing_cell_ids_are_preserved_across_rebuilds()
call Test_cell_lookup_works_inside_long_cell_without_line_map()
call Test_existing_syntax_override_survives_rebuild()
call Test_default_runtime_state_is_initialized_for_new_cells()
call Test_non_default_runtime_state_is_preserved_for_surviving_cells()
call Test_magic_header_has_dedicated_syntax_group()
call Test_syntax_updates_after_cell_type_change()
call Test_visible_cell_body_gets_rich_syntax()
call Test_rich_syntax_covers_all_visible_cells()
call Test_rich_syntax_covers_partially_visible_cell()
call Test_rich_syntax_survives_jump_into_long_cell()
call Test_default_buffer_mappings_exist()
call Test_cell_mode_toggle_maps_navigation_keys()
call Test_cell_mode_switches_sign_highlights()
call Test_blank_body_cell_sign_uses_first_body_line()
call Test_empty_vipynb_buffer_gets_initial_delimiter()
call Test_cell_mode_indicator_state_transitions()
call Test_insert_invalidation_defers_rebuild_until_exit()
call Test_normal_mode_same_line_edit_uses_fast_path()
call Test_normal_mode_line_insert_inside_cell_updates_ranges_without_full_rebuild()
call Test_delimiter_insert_falls_back_to_full_rebuild()
call Test_resize_fast_path_flush_keeps_model_consistent()

if empty(v:errors)
  cquit 0
endif

for error in v:errors
  echom error
endfor

cquit 1
